[package]
name = "manifold"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30.5" }
wgpu = { version = "22.1.0" }
pollster = { version = "0.3.0" }
bytemuck = { version = "1.19.0", features = ["derive"] }
env_logger = { version = "0.11.5" }
log = { version = "0.4.22" }
