[package]
name = "manifold"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = { version = "0.30.5" }
wgpu = "22.1.0"
pollster = "0.3.0"
bytemuck = "1.19.0"
env_logger = "0.11.5"
log = "0.4.22"
